In [1]:
import torch

In [2]:
a = torch.arange(10)
b = torch.arange(10)*10
print( a, b )

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [3]:
a+b

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [4]:
a.shape

torch.Size([10])

In [5]:
a[None].shape

torch.Size([1, 10])

In [6]:
a[:,None].shape

torch.Size([10, 1])

In [7]:
c = a[:,None]
c.shape

torch.Size([10, 1])

In [8]:
c[:,0]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
d = a[None]
d.shape

torch.Size([1, 10])

In [10]:
d[0]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
d[0,:]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
torch.ones([3,2]) + 10

tensor([[11., 11.],
        [11., 11.],
        [11., 11.]])

In [13]:
torch.ones([3,2]) + torch.ones([2,3])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [14]:
torch.ones([3,1]) + torch.ones([1,3])

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [15]:
a[None,:] + b[:,None]

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
a[None,:].repeat(10,1)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [17]:
b[:,None].repeat(1,10)

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
        [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
        [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
        [60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
        [70, 70, 70, 70, 70, 70, 70, 70, 70, 70],
        [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
        [90, 90, 90, 90, 90, 90, 90, 90, 90, 90]])

In [18]:
a[None,:].repeat(10,1) + b[:,None].repeat(1,10)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
a[None,:] * b[:,None]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
        [  0,  20,  40,  60,  80, 100, 120, 140, 160, 180],
        [  0,  30,  60,  90, 120, 150, 180, 210, 240, 270],
        [  0,  40,  80, 120, 160, 200, 240, 280, 320, 360],
        [  0,  50, 100, 150, 200, 250, 300, 350, 400, 450],
        [  0,  60, 120, 180, 240, 300, 360, 420, 480, 540],
        [  0,  70, 140, 210, 280, 350, 420, 490, 560, 630],
        [  0,  80, 160, 240, 320, 400, 480, 560, 640, 720],
        [  0,  90, 180, 270, 360, 450, 540, 630, 720, 810]])